# admin frontend pod config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-react-frontend
  labels:
    app: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
      - name: admin-frontend
        image: mkhizarhussain/adminfrontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
spec:
  type: NodePort
  selector:
    app: admin-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30009
