# express backend deployment config starts here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express_backend
          image: mkhizarhussain/backend:1.0
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-configs
                  key: MYSQL_HOST_STRING
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: mysql-root-username
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: mysql-root-password
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
# express backend service config starts here
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008