# express backend deployment config starts here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express_backend
          image: backend:1.0
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256mi
              cpu: "0.2"
---
# express backend service config starts here
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
